name: Build OrinrinEditor/Viewer/Collector

on: push

jobs:
  buildEditor:
    strategy:
      matrix:
        isDebug: [0, 1]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: SQLite3のビルド
        run: external/sqlite3/build.sh
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinEditorのビルド
        run: IS_DEBUG=${{ matrix.isDebug }} scripts/build_editor.sh
  buildViewer:
    strategy:
      matrix:
        isDebug: [0, 1]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: SQLite3のビルド
        run: external/sqlite3/build.sh
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinViewerのビルド
        run: IS_DEBUG=${{ matrix.isDebug }} scripts/build_viewer.sh
  buildCollector:
    strategy:
      matrix:
        isDebug: [0, 1]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinCollectorのビルド
        run: IS_DEBUG=${{ matrix.isDebug }} scripts/build_collector.sh
