name: Build OrinrinEditor/Viewer/Collector

on: push

jobs:
  buildEditor:
    strategy:
      fail-fast: false
      matrix:
        mode: [Debug, Release]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: SQLite3のビルド
        run: external/sqlite3/build.sh
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinEditorのビルド
        run: |
          case "${{ matrix.mode }}" in
            "Debug"  ) export IS_DEBUG=1 ;;
            "Release") export IS_DEBUG=0 ;;
            *)
              printf "Error: Unknown mode: %s" "${{ matrix.mode }}" >&2
              exit 1
            ;;
          esac
          scripts/build_editor.sh
  buildViewer:
    strategy:
      fail-fast: false
      matrix:
        mode: [Debug, Release]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: SQLite3のビルド
        run: external/sqlite3/build.sh
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinViewerのビルド
        run: |
          case "${{ matrix.mode }}" in
            "Debug"  ) export IS_DEBUG=1 ;;
            "Release") export IS_DEBUG=0 ;;
            *)
              printf "Error: Unknown mode: %s" "${{ matrix.mode }}" >&2
              exit 1
            ;;
          esac
          scripts/build_viewer.sh
  buildCollector:
    strategy:
      fail-fast: false
      matrix:
        mode: [Debug, Release]
    runs-on: ubuntu-20.04
    steps:
      - name: 依存関係のインストール
        run: |
          sudo apt update
          sudo apt install -y mingw-w64-i686-dev gcc-mingw-w64-i686 g++-mingw-w64-i686
      - name: チェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: リソースのコンパイル
        run: scripts/run_windres.sh
      - name: OrinrinCollectorのビルド
        run: |
          case "${{ matrix.mode }}" in
            "Debug"  ) export IS_DEBUG=1 ;;
            "Release") export IS_DEBUG=0 ;;
            *)
              printf "Error: Unknown mode: %s" "${{ matrix.mode }}" >&2
              exit 1
            ;;
          esac
          scripts/build_collector.sh
